name = "otel"
version = "0.1.0"
spin_compatibility = ">=2.5"
license = "MIT"
package = "otel"
assets = [
    "otel-config/compose.yaml", 
    "otel-config/grafana.yaml", 
    "otel-config/loki.yaml", 
    "otel-config/otel-collector-config.yaml", 
    "otel-config/prometheus.yaml", 
    "otel-config/tempo.yaml"
]