name = "otel"
version = "0.1.4"
spin_compatibility = ">=2.5"
license = "Apache-2.0"
package = "otel"
assets = [
    "otel-config/compose.aspire.yaml",
    "otel-config/compose.yaml",
    "otel-config/grafana.yaml",
    "otel-config/loki.yaml",
    "otel-config/otel-collector-config.yaml",
    "otel-config/prometheus.yaml",
    "otel-config/tempo.yaml",
]
